- classes/User.php
- sql/mariadbSqlStatements.sql
- Klassen parameter erweitert.
> refactor: change User class

- sql/mariadbSqlStatements.sql
- workStart and workEnd spalten sind TIME datatype.
> fix: Database

- classes/User.php
- Datatype workStart workEnd nach string geändert.
> fix: Userclass

- classes/User.php
- prepared statement - getUserById
> refactor: User class

- classes/Appointment.php
- classes/User.php
- index.php
-wir haben die falsche Methode benutzt
-Testdateien von index entfernt
> fix: prepared statements

- classes/User.php
- getNamesOfBarbers geschrieben
- einfaches list von Barbers war von frontend nötig
> update: User class

- classes/Appointment.php
- neue funktion newAppointment hinzugefügt.
- eingeloggte user kann neue Termin hinzufügen.
> update: Appointment class

- ajax.php
- ajax logic verinfacht, nach Bescprechung mit FrontEnd.
> refactor: ajax.php

- index.php
> input sanitization

- assets/js/main.js
refactor: deleteAppointment -> clearInput
refactor: initateDeleteButtons -> querySelectorAll & forEach
refactor: createBarberSelector -> remove duplication
style: new commentary for loadDoc
> adjustments

- classes/Appointment.php
- rückgabe ist von role abhängig.
- nachfrage von Frontend.
> refactor: User class / getAppointmentsByBarberAndUserId

- ajax.php
- classes/Appointment.php
- programmlogic geändert
- resonsecode wird geliefert.
> update: ajax logic und appointment

- assets/js/main.js
- removed static table creation
- own accord
> Removed Obsolete line

- sql/mariadbSqlStatements.sql
- workStart and workEnd datatype is now TIME.
> hotfix: database table

- ajax.php
- classes/User.php
- saveUser function now properly identifies barber or user.
- return response code 200 or 400
> hotfix: saveUser

- sql/mariadbSqlStatements.sql
> update: mariadbSqlStatements

- classes/Appointment.php
- classes/User.php
- views/customerPage.php
- unnecessary methods removed.
- comments added.
> cleanup and comments

- sql/mariadbSqlStatements.sql
- Spalte 'password' hinzugefügt
- returnt jetzt LAST_INSERT_ID()
> stored procedure store_user angepasst

- classes/Appointment.php
- classes/User.php
> Short user without pwd

- classes/User.php
- a classmethod was accidentally deleted. Readded.
> hotfix: User class

- ajax.php
> hotfix: ajax

- classes/User.php
> fix: updateUser

- sql/mariadbSqlStatements.sql
- Stored Procedure "store_user" entfernt
- SQL Trigger "insert_user" und "update_user" überprüfen bei jedem INSERT oder UPDATE für die users-Table, ob der User ein barber ist und wenn ja, ob beide Arbeitszeiten vorhanden sind. Wenn nicht, kommt eine Custom-Errormsg
> Stored Procedure store_user ersetzt durch Trigger

- ajax.php
- classes/User.php
- neue funktionale Anforderung
- Programmlogik ergänzt
> new function: deleteUser
